{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ParsableArguments\/exitCode(for:)"},"variants":[{"paths":["\/documentation\/argumentparser\/parsablearguments\/exitcode(for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser","doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ParsableArguments"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"exitCode","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:14ArgumentParser8ExitCodeV","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode","kind":"typeIdentifier","text":"ExitCode"}],"platforms":["macOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"An error to generate an exit code for.","type":"text"}]}]}]},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The exit code for ","type":"text"},{"type":"codeVoice","code":"error"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The returned code is the same exit code that is used if "},{"type":"codeVoice","code":"error"},{"type":"text","text":" is passed"},{"text":" ","type":"text"},{"type":"text","text":"to "},{"type":"codeVoice","code":"exit(withError:)"},{"type":"text","text":"."}]}],"kind":"content"}],"metadata":{"externalID":"s:14ArgumentParser17ParsableArgumentsPAAE8exitCode3forAA04ExitF0Vs5Error_p_tFZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exitCode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"text":"ExitCode","kind":"typeIdentifier","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"role":"symbol","symbolKind":"method","title":"exitCode(for:)","roleHeading":"Type Method","extendedModule":"ArgumentParser","modules":[{"name":"ArgumentParser"}]},"abstract":[{"text":"Returns the exit code for the given error.","type":"text"}],"references":{"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ParsableArguments":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ParsableArguments","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/argumentparser\/parsablearguments","navigatorTitle":[{"kind":"identifier","text":"ParsableArguments"}],"title":"ParsableArguments","kind":"symbol","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ParsableArguments","abstract":[{"text":"A type that can be parsed from a programâ€™s command-line arguments.","type":"text"}]},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode":{"url":"\/documentation\/argumentparser\/exitcode","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ExitCode","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ExitCode"}],"type":"topic","title":"ExitCode","abstract":[{"text":"An error type that only includes an exit code.","type":"text"}]},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser":{"kind":"symbol","role":"collection","url":"\/documentation\/argumentparser","abstract":[],"title":"ArgumentParser","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser","type":"topic"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ParsableArguments/exitCode(for:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"exitCode","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"ExitCode","preciseIdentifier":"s:14ArgumentParser8ExitCodeV","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/argumentparser\/parsablearguments\/exitcode(for:)","title":"exitCode(for:)","kind":"symbol","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ParsableArguments\/exitCode(for:)","abstract":[{"text":"Returns the exit code for the given error.","type":"text"}]}}}