{"variants":[{"paths":["\/documentation\/argumentparser\/exitcode"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/init(_:)","doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/init(rawValue:)"],"title":"Initializers","generated":true},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/isSuccess","doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/rawValue"],"anchor":"Instance-Properties"},{"generated":true,"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/failure","doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/success","doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/validationFailure"]},{"identifiers":["doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/Equatable-Implementations","doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/Error-Implementations","doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ArgumentParser"}],"externalID":"s:14ArgumentParser8ExitCodeV","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExitCode"}],"roleHeading":"Structure","title":"ExitCode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ExitCode"}],"symbolKind":"struct"},"abstract":[{"type":"text","text":"An error type that only includes an exit code."}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExitCode"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"inlineContent":[{"text":"If youâ€™re printing custom error messages yourself, you can throw this error","type":"text"},{"text":" ","type":"text"},{"text":"to specify the exit code without adding any additional output to standard","type":"text"},{"type":"text","text":" "},{"type":"text","text":"out or standard error."}],"type":"paragraph"}]}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.SwiftyLab.HelperCoders\/SQ","doc:\/\/com.SwiftyLab.HelperCoders\/s5ErrorP","doc:\/\/com.SwiftyLab.HelperCoders\/SH","doc:\/\/com.SwiftyLab.HelperCoders\/SY","doc:\/\/com.SwiftyLab.HelperCoders\/s8SendableP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser"]]},"sections":[],"references":{"doc://com.SwiftyLab.HelperCoders/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/SQ","type":"unresolvable"},"doc://com.SwiftyLab.HelperCoders/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/SH","type":"unresolvable"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode":{"url":"\/documentation\/argumentparser\/exitcode","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ExitCode","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ExitCode"}],"type":"topic","title":"ExitCode","abstract":[{"text":"An error type that only includes an exit code.","type":"text"}]},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/success":{"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/success","type":"topic","title":"success","kind":"symbol","url":"\/documentation\/argumentparser\/exitcode\/success","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14ArgumentParser8ExitCodeV","text":"ExitCode","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"An exit code that indicates successful completion of a command."}]},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/init(_:)":{"url":"\/documentation\/argumentparser\/exitcode\/init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/init(_:)","abstract":[{"text":"Creates a new ","type":"text"},{"code":"ExitCode","type":"codeVoice"},{"type":"text","text":" with the given code."}],"type":"topic","kind":"symbol","title":"init(_:)","role":"symbol"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/Error-Implementations":{"abstract":[],"url":"\/documentation\/argumentparser\/exitcode\/error-implementations","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/Error-Implementations","title":"Error Implementations","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/RawRepresentable-Implementations":{"url":"\/documentation\/argumentparser\/exitcode\/rawrepresentable-implementations","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/RawRepresentable-Implementations","abstract":[],"type":"topic","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/argumentparser\/exitcode\/equatable-implementations","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/rawValue":{"url":"\/documentation\/argumentparser\/exitcode\/rawvalue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/rawValue","abstract":[{"type":"text","text":"The exit code represented by this instance."}],"type":"topic","kind":"symbol","title":"rawValue","role":"symbol"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/init(rawValue:)":{"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/argumentparser\/exitcode\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":")"}],"title":"init(rawValue:)","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/init(rawValue:)"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/validationFailure":{"kind":"symbol","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/validationFailure","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/validationfailure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"validationFailure","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14ArgumentParser8ExitCodeV","text":"ExitCode","kind":"typeIdentifier"}],"title":"validationFailure","role":"symbol","abstract":[{"type":"text","text":"An exit code that indicates that the user provided invalid input."}]},"doc://com.SwiftyLab.HelperCoders/SY":{"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/isSuccess":{"abstract":[{"type":"text","text":"A Boolean value indicating whether this exit code represents the"},{"text":" ","type":"text"},{"type":"text","text":"successful completion of a command."}],"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/isSuccess","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isSuccess"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isSuccess","type":"topic","url":"\/documentation\/argumentparser\/exitcode\/issuccess","role":"symbol"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser":{"kind":"symbol","role":"collection","url":"\/documentation\/argumentparser","abstract":[],"title":"ArgumentParser","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser","type":"topic"},"doc://com.SwiftyLab.HelperCoders/s5ErrorP":{"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://com.SwiftyLab.HelperCoders/s8SendableP":{"identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.SwiftyLab.HelperCoders/documentation/ArgumentParser/ExitCode/failure":{"role":"symbol","title":"failure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failure"},{"text":": ","kind":"text"},{"text":"ExitCode","kind":"typeIdentifier","preciseIdentifier":"s:14ArgumentParser8ExitCodeV"}],"kind":"symbol","identifier":"doc:\/\/com.SwiftyLab.HelperCoders\/documentation\/ArgumentParser\/ExitCode\/failure","type":"topic","abstract":[{"text":"An exit code that indicates that the command failed.","type":"text"}],"url":"\/documentation\/argumentparser\/exitcode\/failure"}}}